name: Package
description: Package Aleph

inputs:
  build-type: 
    description: 
    required: true

runs:
  using: composite
  steps:
    - name: Determine setup
      id: setup
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          echo "path=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          echo "shell=cmd" >> "$GITHUB_OUTPUT"
        else
          echo "path=${{ github.workspace }}/build/${{ inputs.build-type }}" >> "$GITHUB_OUTPUT"
          echo "shell=bash" >> "$GITHUB_OUTPUT"
        fi

    - name: Package Binaries
      if: inputs.build-type == 'Release'
      shell: ${{ steps.setup.outputs.shell }}
      working-directory: ${{ steps.setup.outputs.path }}
      run: |
        cpack

    - name: Attest Binary Package
      if: inputs.build-type == 'Release'
      uses: actions/attest@v4
      with:
        subject-path: '${{ steps.setup.outputs.path }}/aleph-*.tar.gz'

    - name: Upload Binary Artifact
      if: inputs.build-type == 'Release'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: ${{ steps.setup.outputs.path }}/aleph-*.tar.gz
        archive: false

    - name: Package Source
      if: inputs.build-type == 'Debug'
      shell: bash
      working-directory: ${{ steps.setup.outputs.path }}
      run: |
        cpack --config CPackSourceConfig.cmake