name: Scorecard
description: Run OpenSSF Scorecard analysis

runs:
  using: composite
  steps:
    - name: Run analysis
      uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
      with:
        results_file: results.sarif
        results_format: sarif
        repo_token: ${{ github.token }}
        publish_results: true

    - name: Upload artifact
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: SARIF file
        path: results.sarif
        retention-days: 5

    - name: Upload to code-scanning
      uses: github/codeql-action/upload-sarif@603b797f8b14b413fe025cd935a91c16c4782713 # v3.33.0
      with:
        sarif_file: results.sarif