set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")

set(CPACK_PACKAGE_FILE_NAME "aleph-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_CXX_COMPILER_ID}")
string(TOLOWER ${CPACK_PACKAGE_FILE_NAME} CPACK_PACKAGE_FILE_NAME)
set(CPACK_SOURCE_PACKAGE_FILE_NAME "aleph-${PROJECT_VERSION}-source")
set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_SOURCE_IGNORE_FILES
    "/.git/"
    "/.vscode/"
    "/build/"
    "/CMakeUserPresets.json"
    "/venv/"
)

set(CPACK_GENERATOR "External")
set(CPACK_SOURCE_GENERATOR "External")
set(CPACK_EXTERNAL_ENABLE_STAGING ON)
set(CPACK_EXTERNAL_PACKAGE_SCRIPT "${CMAKE_SOURCE_DIR}/cmake/package_script.cmake")


include(CPack)