name: Daily Checks

on:
  schedule:
    - cron: '45 5 * * *'


permissions:
  contents: none

concurrency:
  group: action-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clusterfuzzlite:
    name: ClusterFuzzLite (${{ matrix.mode }}, ${{ matrix.sanitizer }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: action-ClusterFuzzLite-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        include:
          - mode: batch
            sanitizer: address
          - mode: batch
            sanitizer: memory
          - mode: batch
            sanitizer: undefined
          - mode: prune
            sanitizer: address # Address is the default, should keep it here
          - mode: coverage
            sanitizer: coverage

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit
        
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run Fuzzer
        uses: ./.github/actions/clusterfuzzlite
        with:
          mode: ${{ matrix.mode }}
          fuzz-seconds: 600
          sanitizer: ${{ matrix.sanitizer }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  codeql:
    name: CodeQL Analysis
    uses: ./.github/workflows/codeql.yml
    concurrency:
      group: action-CodeQL Analysis-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

  osv-scanner:
    name: OSV Scanner
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@c5996e0193a3df57d695c1b8a1dec2a4c62e8730 # v2.3.3
    permissions:
      # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
      actions: read
      contents: read
      security-events: write

  scorecard:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    concurrency:
      group: action-OpenSSF Scorecard-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit
        
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ github.token }}
          publish_results: true

      - name: Upload artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@603b797f8b14b413fe025cd935a91c16c4782713 # v3.33.0
        with:
          sarif_file: results.sarif