name: Code Quality

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - staging

permissions: read-all

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        uses: jidicula/clang-format-action@3a18028048f01a66653b4e3bf8d968d2e7e2cb8b
        with:
          clang-format-version: '22'
          check-path: '.'
          exclude-regex: '(build|\.conan)'