name: Code Quality

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - staging

permissions: read-all

jobs:
  cpp-linter:
    name: cpp-linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: '-*'
          version: '22'
          lines-changed-only: false
          thread-comments: true

      - name: Fail if issues found
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1